updated pipelines with error hanfdling

diff --git a/.github/workflows/setup-alb-gateway.yml b/.github/workflows/setup-alb-gateway.yml
--- a/.github/workflows/setup-alb-gateway.yml
+++ b/.github/workflows/setup-alb-gateway.yml
@@ -1,4 +1,4 @@
-name: Setup ALB Gateway``
+name: Setup ALB Gateway
 on:
   workflow_dispatch:
     inputs:
@@ -39,10 +39,15 @@ jobs:
 
       - name: Create azure-alb-system Namespace
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          NAMESPACE_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
-            --command "kubectl create namespace azure-alb-system && \
-            kubectl wait --for='jsonpath={.status.phase}=Active' ns/azure-alb-system --timeout 60s"
+            --command "kubectl create namespace azure-alb-system --dry-run=client -o yaml | kubectl apply -f - && \
+            kubectl wait --for='jsonpath={.status.phase}=Active' ns/azure-alb-system --timeout 60s")
+          echo "$NAMESPACE_OUT"
+          if echo "$NAMESPACE_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=Namespace creation failed::${NAMESPACE_OUT}"
+              exit 1
+          fi
 
       - name: Install alb-controller using Helm
         run: |
@@ -50,6 +55,10 @@ jobs:
           CURRENT_VERSION=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "helm list -n azure-alb-system --filter "^alb-controller$" -o json | jq -r '.[0].chart'")
+          echo "$CURRENT_VERSION"
+          if echo "$CURRENT_VERSION" | grep -q "exitcode=[^0]"; then
+              echo "::error title=helm list failed::${CURRENT_VERSION}"
+          fi
 
           if [[ "$CURRENT_VERSION" == "alb-controller-1.9.13" ]]; then
             echo "Versions match. Skipping upgrade to prevent revision bloat."
@@ -59,8 +68,13 @@ jobs:
               --name azure-alb-identity \
               --resource-group ${{ inputs.resource_group_name }} \
               --query clientId -o tsv)
+            echo "$ALB_CLIENT_ID"
+            if echo "$ALB_CLIENT_ID" | grep -q "exitcode=[^0]"; then
+                echo "::error title=alb-controller client id not found::${ALB_CLIENT_ID}"
+                exit 1
+            fi
 
-            az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+            HELM_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "helm upgrade --install alb-controller \
               oci://mcr.microsoft.com/application-lb/charts/alb-controller \
@@ -69,36 +83,61 @@ jobs:
               --set albController.namespace=azure-alb-system \
               --set albController.podIdentity.clientID=${ALB_CLIENT_ID} \
               --wait \
-              --timeout 5m"
+              --timeout 5m")
+            echo "$HELM_OUT"
+            if echo "$HELM_OUT" | grep -q "exitcode=[^0]"; then
+                echo "::error title=helm install failed::${HELM_OUT}"
+                exit 1
+            fi
           fi
 
       - name: Wait for alb-controller Pods Ready
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          POD_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "kubectl wait pod \
             --selector app=alb-controller \
             -n azure-alb-system \
             --for=condition=Ready \
-            --timeout=600s"
+            --timeout=600s")
+            echo "$POD_OUT"
+            if echo "$POD_OUT" | grep -q "exitcode=[^0]"; then
+                echo "::error title=pod wait failed::${POD_OUT}"
+                exit 1
+            fi
 
       - name: Verify alb-controller is running
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          SEC_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
-            --command "kubectl get pods -n azure-alb-system"
+            --command "kubectl get pods -n azure-alb-system")
+          echo "$SEC_OUT"
+          if echo "$SEC_OUT" | grep -q "exitcode=[^0]"; then
+            echo "::error title=alb-controller is not running::${SEC_OUT}"; 
+            exit 1
+          fi
 
       - name: Wait for GatewayClass to be accepted
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          GATEWAY_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
-            --command "kubectl wait gatewayclass azure-alb-external --for=condition=Accepted --timeout=600s"
+            --command "kubectl wait gatewayclass azure-alb-external --for=condition=Accepted --timeout=600s")
+          echo "$GATEWAY_OUT"
+          if echo "$GATEWAY_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=GatewayClass wait failed::${GATEWAY_OUT}"; 
+              exit 1
+          fi
 
       - name: Verify GatewayClass azure-alb-external is installed
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          GATEWAY_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
-            --command "kubectl get gatewayclass azure-alb-external -o yaml"
+            --command "kubectl get gatewayclass azure-alb-external -o yaml")
+          echo "$GATEWAY_OUT"
+          if echo "$GATEWAY_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=GatewayClass not installed::${GATEWAY_OUT}"; 
+              exit 1
+          fi
 
       - name: Create ApplicationLoadBalancer Kubernetes Resource
         run: |
@@ -107,34 +146,54 @@ jobs:
             --vnet-name ${{ inputs.app_vnet_name }} \
             --name ${{ inputs.subnet_name }} \
             --query id -o tsv)
-
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
-            --name ${{ inputs.aks_cluster_name }} \
-            --command "
-            kubectl apply -f - <<EOF
-            apiVersion: alb.networking.azure.io/v1
-            kind: ApplicationLoadBalancer
-            metadata:
-              name: alb-infra
-              namespace: azure-alb-system
-            spec:
-              associations:
-                - ${ALB_SUBNET_ID}
-            EOF
-            "
+          echo "$ALB_SUBNET_ID"
+          if echo "$ALB_SUBNET_ID" | grep -q "exitcode=[^0]"; then
+              echo "::error title=Subnet not found::${ALB_SUBNET_ID}"; 
+              exit 1
+          fi
+          ALB_OUT=$(az aks command invoke \
+          --resource-group "${{ inputs.resource_group_name }}" \
+          --name "${{ inputs.aks_cluster_name }}" \
+          --command "
+          kubectl apply -f - <<EOF
+          apiVersion: alb.networking.azure.io/v1
+          kind: ApplicationLoadBalancer
+          metadata:
+            name: alb-infra
+            namespace: azure-alb-system
+          spec:
+            associations:
+              - ${ALB_SUBNET_ID}
+          EOF
+          ")
+          echo "$ALB_OUT"
+          if echo "$ALB_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ApplicationLoadBalancer creation failed::${ALB_OUT}"; 
+              exit 1
+          fi
 
       - name: Wait for the ApplicationLoadBalancer Deployment
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          ALB_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "kubectl wait applicationloadbalancer/alb-infra \
             -n azure-alb-system \
             --for='jsonpath={.status.conditions[?(@.type=="Deployment")].reason}=Ready' \
-            --timeout=600s"
+            --timeout=600s")
+          echo "$ALB_OUT"
+          if echo "$ALB_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ApplicationLoadBalancer deployment wait failed::${ALB_OUT}"; 
+              exit 1
+          fi
 
       - name: Verify ApplicationLoadBalancer is running
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          ALB_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "kubectl get applicationloadbalancer alb-infra \
-            -n azure-alb-system -o yaml"
+            -n azure-alb-system -o yaml")
+          echo "$ALB_OUT"
+          if echo "$ALB_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ApplicationLoadBalancer verification failed::${ALB_OUT}"; 
+              exit 1
+          fi
diff --git a/.github/workflows/setup-argocd.yml b/.github/workflows/setup-argocd.yml
--- a/.github/workflows/setup-argocd.yml
+++ b/.github/workflows/setup-argocd.yml
@@ -24,6 +24,9 @@ jobs:
     name: Setup ArgoCD
     runs-on: ubuntu-latest
     steps:
+      - name: checkout
+        uses: actions/checkout@v6
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
@@ -33,10 +36,15 @@ jobs:
 
       - name: Create argocd Namespace
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          NAMESPACE_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f - && \
-            kubectl wait --for='jsonpath={.status.phase}=Active' ns/argocd --timeout 60s"
+            kubectl wait --for='jsonpath={.status.phase}=Active' ns/argocd --timeout 60s")
+          echo "$NAMESPACE_OUT"
+          if echo "$NAMESPACE_OUT" | grep -q "exitcode=[^0]"; then
+            echo "::error title=Namespace creation failed::${NAMESPACE_OUT}"; 
+            exit 1
+          fi
 
       - name: Install ArgoCD using Helm
         run: |
@@ -44,12 +52,16 @@ jobs:
           CURRENT_VERSION=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "helm list -n argocd --filter \'argocd$\' -o json | jq -r '.[0].chart'")
+          echo "$CURRENT_VERSION"
+          if echo "$CURRENT_VERSION" | grep -q "exitcode=[^0]"; then
+            echo "::error title=helm list failed::${CURRENT_VERSION}"; 
+          fi
 
           if [[ "$CURRENT_VERSION" == "argo-cd-9.5.14" ]]; then
             echo "Versions match. Skipping upgrade to prevent revision bloat."
           else
             echo "New version detected. Proceeding with upgrade..."
-            az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+            HELM_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
               --name ${{ inputs.aks_cluster_name }} \
               --command "helm upgrade --install argocd \
               oci://ghcr.io/argoproj/argo-helm/argo-cd \
@@ -61,21 +73,49 @@ jobs:
               --set configs.params."server\.insecure"=true \
               --set crds.enabled=true \
               --wait \
-              --timeout 5m"
+              --timeout 5m")
+            echo "$HELM_OUT"
+            if echo "$HELM_OUT" | grep -q "exitcode=[^0]"; then
+                echo "::error title=helm install failed::${HELM_OUT}"; 
+                exit 1
+            fi
           fi
 
       - name: Wait for the ArgoCD resources Ready
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          DEPLOYMENT_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
             --command "kubectl wait deployment \
             --all \
             -n argocd \
             --for=condition=Available \
             --timeout=600s"
+          echo "$DEPLOYMENT_OUT"
+          if echo "$DEPLOYMENT_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ApplicationLoadBalancer deployment wait failed::${DEPLOYMENT_OUT}"; 
+              exit 1
+          fi
 
       - name: Verify ArgoCD pods
         run: |
-          az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+          PODS_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
             --name ${{ inputs.aks_cluster_name }} \
-            --command "kubectl get pods -n argocd"
+            --command "kubectl get pods -n argocd")
+          echo "$PODS_OUT"
+          if echo "$PODS_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ApplicationLoadBalancer verification failed::${PODS_OUT}"; 
+              exit 1
+          fi
+
+      - name: Create ArgoCD Project for Streamforge
+        working-directory: gitops/argocd
+        run: |
+          ARGO_PROJECT_OUT=$(az aks command invoke --resource-group ${{ inputs.resource_group_name }} \
+            --name ${{ inputs.aks_cluster_name }} \
+            --command "kubectl apply -f project.yml" \
+            --file project.yml)
+          echo "$ARGO_PROJECT_OUT"
+          if echo "$ARGO_PROJECT_OUT" | grep -q "exitcode=[^0]"; then
+              echo "::error title=ArgoCD project creation failed::${ARGO_PROJECT_OUT}"; 
+              exit 1
+          fi
